import pytest


@pytest.fixture
def simple_article() -> str:
    return "this is a simple article written by a simple person this article is used to validate the test"


@pytest.fixture
def simple_string() -> str:
    return "this is cool this this cool "


@pytest.fixture
def complex_article() -> str:
    return (
        "Prime Minister head cabinet head Since 2018 general election Malaysia governed Pakatan Harapan political "
        "alliance 24 February 2020 7th Prime Tun Mahathir Mohamad resign Prime Minister starting 1 March new "
        "coalition governed Malaysia led new 8th Prime Minister Tan Sri Muhyiddin Yassin legal system based "
        "English Common Law Although judiciary theoretically independence called question appointment judges lacks "
        "accountability highest court judicial system Federal Court followed Court Appeal two high courts one "
        "Peninsular Malaysia one East Malaysia special court hear cases brought death penalty use serious crimes "
        "murder terrorism drug trafficking kidnapping Separate running parallel civil courts Syariah Courts apply "
        "Shariah law Muslims areas family law religious Homosexuality illegal authorities impose punishment caning "
        "Race significant force Affirmative actions New Economic Policy National Development Policy superseded "
        "implemented advance standing consisting Malays indigenous tribes considered original inhabitants "
        "Malaysian Chinese Malaysian policies provide preferential treatment access cheaper housing assisted "
        "generated greater interethnic ongoing debate whether laws society Malaysia reflect secular Islamic "
        "Islamic criminal laws passed Islamic Party support United Malays National Organisation state assemblymen "
        "state legislative assembly Kelantan blocked federal government basis criminal laws responsibility federal "
        "States federal territories Malaysia Divisions Malaysia Districts Malaysia Perlis Kedah Penang Kelantan "
        "Terengganu Perak Selangor Negeri Sembilan Melaka Johor Pahang Sarawak Sabah West Malaysia East Malaysia "
        "States Malaysia federation 13 states three federal divided two 11 states two federal territories "
        "Peninsular Malaysia two states one federal territory East Malaysia state divided districts divided mukim "
        "Sabah Sarawak districts grouped Governance states divided federal state different powers reserved Federal "
        "government direct administration federal state unicameral State Legislative Assembly whose members "
        "elected State governments led Chief Ministers state assembly members majority party states hereditary "
        "Chief Minister normally required Malay appointed ruler upon recommendation Prime Except state elections "
        "convention state elections held concurrently federal administration carried local include city district "
        "municipal although autonomous statutory bodies created federal state governments deal certain federal "
        "constitution puts local authorities outside federal territories exclusive jurisdictions state although "
        "practice federal government intervened affairs state local 154 local consisting 14 city 38 municipal 97 "
        "district 13 states based historical Malay 9 11 Peninsular known Malay states retain royal King elected "
        "nine rulers serve King appoints governors serving term states without consultations chief minister state "
        "written Sabah Sarawak considerably autonomy notably separate immigration policies unique residency "
        "Federal intervention state lack disputes oil royalties occasionally led statements secession leaders "
        "several states Penang Johor Kelantan Sabah although followed serious independence movements list thirteen "
        "states state capital Johor Johor Bahru Kedah Alor Setar Kelantan Kota Bharu Malacca Malacca City Negeri "
        "Sembilan Seremban Pahang Kuantan Penang George Town Perak Ipoh Perlis Kangar Sabah Kota Kinabalu Sarawak "
        "Kuching Selangor Shah Alam Terengganu Kuala Terengganu Federal Territory Kuala Lumpur Federal Territory "
        "Labuan Federal Territory Putrajaya Foreign relations Malaysia Malaysian Armed Forces Mike Pompeo "
        "Putrajaya founding member Association Southeast Asian Nations Organisation Islamic Cooperation country "
        "participates many international organisations United Nations Economic Cooperation Developing 8 Countries "
        "Movement chaired NAM former British member Commonwealth Nations Kuala Lumpur site first East Asia Summit "
        "foreign policy officially based principle neutrality maintaining peaceful relations regardless political "
        "government attaches high priority security stability Southeast seeks develop relations countries "
        "Historically government tried portray Malaysia progressive Islamic nation strengthening relations Islamic "
        "strong tenet policy national sovereignty right country control domestic Malaysia signed UN treaty "
        "Prohibition Nuclear Weapons Spratly Islands disputed many states large portion South China Sea claimed "
        "China Unlike neighbours Vietnam Philippines Malaysia historically avoided conflicts encroachment Chinese "
        "ships Malaysian territorial Malaysia become active condemning Brunei Malaysia 2009 announced end claims "
        "committed resolve issues related maritime Philippines dormant claim eastern part land reclamation caused "
        "minor maritime land border disputes exist Malaysian Armed Forces submarine MBT tank Malaysian Army M4 "
        "fighter aircraft Malaysia never recognised Israel diplomatic ties called International Criminal Court "
        "take action Israel Gaza flotilla raid Malaysia stated establish official relations Israel peace agreement "
        "State Palestine called parties find quick resolution realise solution Malaysian peacekeeping forces "
        "contributed many UN peacekeeping Congo Namibia Cambodia Bosnia Herzegovina Somalia Kosovo East Timor "
        "Lebanon Malaysian Armed Forces three Royal Malaysian Navy Malaysian Army Royal Malaysian Air Force "
        "required age voluntary military service military uses employs Five Power Defence Arrangements regional "
        "security initiative place almost 40 involves joint military exercises held among New United Joint "
        "exercises war games held Indonesia Japan United Thailand Vietnam agreed host joint security force "
        "exercises secure maritime border tackle issues illegal piracy smuggling Previously fears extremist "
        "militants activities Muslim areas southern Philippines southern Thailand would spill Malaysia began "
        "increase border Geography Malaysia equatorial region tropical rainforest climate Malaysia 66th largest "
        "country total land area land area km sq land borders Thailand West Indonesia Brunei East linked Singapore "
        "narrow causeway country maritime boundaries Vietnam land borders defined large part geological features "
        "Perlis River Golok River Pagalayan whilst maritime boundaries subject ongoing Brunei forms almost enclave "
        "state Sarawak dividing two Malaysia country territory Asian mainland Malay Tanjung Piai located southern "
        "state Johor southernmost tip continental Strait Malacca lying Sumatra Peninsular one important "
        "thoroughfares global carrying 40 per cent two parts separated South China Sea share largely similar "
        "landscape Peninsular East Malaysia feature coastal plains rising hills Peninsular containing 40 per cent "
        "land extends 740 km north maximum width 322 km divided east west coasts Titiwangsa Mountains rising peak "
        "elevation metres Mount Korbu part series mountain ranges running centre mountains heavily mainly composed "
        "granite igneous Much creating karst range origin Peninsular river coastal plains surrounding peninsula "
        "reach maximum width 50 kilometres coastline nearly km although harbours available western Mount Kinabalu "
        "East island Borneo coastline km divided coastal hills mountainous Crocker Range extends northwards "
        "dividing state location high Mount Kinabalu tallest mountain Mount Kinabalu located Kinabalu National "
        "Park protected one four UNESCO World Heritage Sites Malaysia highest mountain ranges form border Malaysia "
        "Sarawak contains Mulu largest cave system Gunung Mulu National Park World Heritage Around two halves "
        "Malaysia numerous islands largest Banggi local climate equatorial characterised annual southwest "
        "northeast monsoons temperature moderated presence surrounding Humidity usually average annual rainfall "
        "250 cm climates Peninsula East climate peninsula directly affected wind opposed maritime weather Local "
        "climates divided three Climate change likely affect sea levels increasing flood risks leading Wildlife "
        "Malaysia oriental pied hornbills hawksbill sea turtle proboscis monkey Malayan tiger Malaysia signed Rio "
        "Convention Biological Diversity 12 June became party convention 24 June subsequently produced National "
        "Biodiversity Strategy Action Plan received convention 16 April country megadiverse high number species "
        "high levels endemism estimated contain 20 per cent animal High levels endemism found diverse forests "
        "species isolated lowland 210 mammal species 620 species birds recorded Peninsular many endemic mountains "
        "high number endemic bird species found Malaysian 250 reptile species recorded 150 species snakes 80 "
        "species 150 species thousands insect Exclusive economic zone Malaysia km sq times larger land mainly "
        "South China Sea waters Coral Triangle biodiversity waters around Sipadan island biodiverse Bordering East "
        "Sulu Sea biodiversity around 600 coral species 1200 fish unique biodiversity Malaysian Caves always "
        "attracts lovers ecotourism Nearly species including species recorded two fungal groups largest number "
        "species Ascomycota asexual states surveyed habitats marine freshwater parasites agents poorly surveyed "
        "habitats human animal Basidiomycota partly bracket fungi mushrooms toadstools Malaysian rust smut fungi "
        "remain poorly Without many fungal species Malaysia yet likely many new Rafflesia two thirds Malaysia "
        "covered forest forests believed 130 million years forests dominated dipterocarps Lowland forest covers "
        "areas 760 formerly East Malaysia covered rainforest supported hot wet around species flowering plants "
        "Besides km sq mangroves large amount peat higher rhododendrons replace estimated species vascular plants "
    )
